### PR TITLE
Add hourglass_pattern.cpp

### PR DESCRIPTION
**Pull request by AbhayD11**
Hourglass pattern in CPP

### CODE REVIEW

**Comment by KAMYAVERMA** [comment]
I guess this repo is excluded from hacktoberfest2022. Is it???

**Comment by AbhayD11** [comment]
Yeah, you are right! though there are many others. dw :)

**Comment by KAMYAVERMA** [comment]
Yup

**Comment by AbhayD11** [comment]
Sent some cheat codes on ur linkedin. do check em.

**Pull request closed without merging**
